import subprocess

files= ['Arch_Amazon-Athena_64.json',
'Arch_Amazon-Braket_64.json',
'Arch_Amazon-Chime-SDK_64.json',
'Arch_Amazon-Cloud-Directory_64.json',
'Arch_Amazon-CloudFront_64.json',
'Arch_Amazon-CodeGuru_64.json',
'Arch_Amazon-CodeWhisperer_64.json',
'Arch_Amazon-Comprehend_64.json',
'Arch_Amazon-Corretto_64.json',
'Arch_Amazon-Detective_64.json',
'Arch_Amazon-DevOps-Guru_64.json',
'Arch_Amazon-EventBridge_64.json',
'Arch_Amazon-Fraud-Detector_64.json',
'Arch_Amazon-Kinesis-Data-Streams_64.json',
'Arch_Amazon-Managed-Grafana_64.json',
'Arch_Amazon-Nimble-Studio_64.json',
'Arch_Amazon-OpenSearch-Service_64.json',
'Arch_Amazon-QuickSight_64.json',
'Arch_Amazon-SageMaker-Ground-Truth_64.json',
'Arch_Amazon-SageMaker_64.json',
'Arch_Amazon-Simple-Queue-Service_64.json',
'Arch_Apache-MXNet-on-AWS_64.json',
'Arch_AWS-AppConfig_64.json',
'Arch_AWS-AppFabric_64.json',
'Arch_AWS-Application-Cost-Profiler_64.json',
'Arch_AWS-Certificate-Manager_64.json',
'Arch_AWS-Clean-Rooms_64.json',
'Arch_AWS-Cloud-Development-Kit_64.json',
'Arch_AWS-Cloud9_64.json',
'Arch_AWS-CodeBuild_64.json',
'Arch_AWS-Cost-Explorer_64.json',
'Arch_AWS-Data-Pipeline_64.json',
'Arch_AWS-DataSync_64.json',
'Arch_AWS-DeepRacer_64.json',
'Arch_AWS-Elemental-MediaConnect_64.json',
'Arch_AWS-Elemental-MediaPackage_64.json',
'Arch_AWS-Elemental-MediaStore_64.json',
'Arch_AWS-Fault-Injection-Service_64.json',
'Arch_AWS-Glue_64.json',
'Arch_AWS-Ground-Station_64.json',
'Arch_AWS-HealthLake_64.json',
'Arch_AWS-HealthScribe_64.json',
'Arch_AWS-Identity-and-Access-Management_64.json',
'Arch_AWS-IoT-Device-Management_64.json',
'Arch_AWS-IoT-TwinMaker_64.json',
'Arch_AWS-Launch-Wizard_64.json',
'Arch_AWS-License-Manager_64.json',
'Arch_AWS-Migration-Evaluator_64.json',
'Arch_AWS-Migration-Hub_64.json',
'Arch_AWS-Proton_64.json',
'Arch_AWS-Resource-Access-Manager_64.json',
'Arch_AWS-RoboMaker_64.json',
'Arch_AWS-Signer_64.json',
'Arch_AWS-Site-to-Site-VPN_64.json',
'Arch_AWS-Transit-Gateway_64.json',
'Arch_AWS-Verified-Access_64.json',
'Arch_AWS-X-Ray_64.json']


for i in files:
    subprocess.run(['cfn-lint', i])
