kubectl apply -f ../k8s/namespace.yaml
kubectl apply -f ../k8s/kong-configmap.yaml
kubectl apply -f ../k8s/kong-deployment.yaml
kubectl apply -f ../k8s/kong-service.yaml
kubectl apply -f ../k8s/frontend-deployment.yaml
kubectl apply -f ../k8s/frontend-service.yaml
kubectl apply -f ../k8s/mongo-deployment.yaml
kubectl apply -f ../k8s/mongo-service.yaml
kubectl apply -f ../k8s/awsicons-deployment.yaml
kubectl apply -f ../k8s/awsicons-service.yaml
kubectl apply -f ../k8s/generateawstemplate-deployment.yaml
kubectl apply -f ../k8s/generateawstemplate-service.yaml
kubectl apply -f ../k8s/llm-deployment.yaml
kubectl apply -f ../k8s/llm-service.yaml
kubectl apply -f ../k8s/ingress.yaml
