apiVersion: apps/v1
kind: Deployment
metadata:
  name: correlation
  namespace: diagrams2code
spec:
  replicas: 1
  selector:
    matchLabels:
      app: correlation
  template:
    metadata:
      labels:
        app: correlation
    spec:
      containers:
        - name: correlation
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          image: capthestone/website-correlation:latest
          envFrom:
          - configMapRef:
              name: kafka-config
          - configMapRef:
              name: redis-config
