apiVersion: apps/v1
kind: Deployment
metadata:
  name: getresult
  namespace: diagrams2code
spec:
  replicas: 1
  selector:
    matchLabels:
      app: getresult
  template:
    metadata:
      labels:
        app: getresult
    spec:
      containers:
        - name: getresult
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          image: capthestone/website-getresult:latest
          envFrom:
          - configMapRef:
              name: kafka-config
          - configMapRef:
              name: redis-config
