AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template to create an Amazon FSx file system

Parameters:
  FileSystemName:
    Description: The name of the FSx file system
    Type: String
    Default: MyFSxFileSystem

  FileSystemType:
    Description: The type of FSx file system (WINDOWS or LUSTRE)
    Type: String
    AllowedValues:
      - WINDOWS
      - LUSTRE
    Default: WINDOWS

  StorageCapacity:
    Description: The storage capacity of the file system in GiB (minimum 300 GiB for Windows, 120 GiB for Lustre)
    Type: Number
    Default: 300
    MinValue: 120
    MaxValue: 1000000

  # SubnetId:
  #   Description: The ID of the subnet in which to create the file system
  #   Type: AWS::EC2::Subnet::Id

  # SecurityGroupIds:
  #   Description: The security group IDs for the file system
  #   Type: List<AWS::EC2::SecurityGroup::Id>

  ActiveDirectoryId:
    Description: The ID of the Active Directory to use with the FSx file system (required for Windows)
    Type: String
    Default: ""

  AutoImportPolicy:
    Description: The auto-import policy for Lustre file systems
    Type: String
    Default: "NONE"
    AllowedValues:
      - "NONE"
      - "NEW"
      - "NEW_AND_CHANGED"

Resources:

  # Amazon FSx File System
  MyFileSystem:
    Type: 'AWS::FSx::FileSystem'
    Properties:
      FileSystemType: !Ref FileSystemType
      StorageCapacity: !Ref StorageCapacity
      # SubnetId: !Ref SubnetId
      # SecurityGroupIds: !Ref SecurityGroupIds

      # Configuration for Windows File Server
      WindowsConfiguration:
        ActiveDirectoryId: !If 
          - "Equals" 
          - !Ref FileSystemType 
          - !Ref ActiveDirectoryId 
          # - !Ref AWS::NoValue
        AutomaticBackupRetentionDays: 7
        DailyAutomaticBackupStartTime: "04:00"
        MultiAZ: true

      # Configuration for Lustre File System
      LustreConfiguration:
        DeploymentType: PERSISTENT
        AutoImportPolicy: !If 
          - "Equals" 
          - !Ref FileSystemType 
          - !Ref AutoImportPolicy 
          # - !Ref AWS::NoValue
        WeeklyMaintenanceStartTime: "1:00"

# Outputs:
#   FileSystemId:
#     Description: The ID of the created FSx file system
#     Value: !Ref MyFileSystem

#   FileSystemArn:
#     Description: The ARN of the created FSx file system
#     Value: !GetAtt MyFileSystem.Arn
