AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template to set up infrastructure for Amazon EKS Distro

Parameters:
  # VPCName:
  #   Description: Name of the VPC
  #   Type: String
  #   Default: MyEKS-Distro-VPC

  # VpcCidr:
  #   Description: CIDR block for the VPC
  #   Type: String
  #   Default: 10.0.0.0/16

  # PublicSubnetName:
  #   Description: Name of the public subnet
  #   Type: String
  #   Default: MyPublicSubnet

  # PublicSubnetCidr:
  #   Description: CIDR block for the public subnet
  #   Type: String
  #   Default: 10.0.1.0/24

  InstanceType:
    Description: EC2 instance type for EKS Distro
    Type: String
    Default: t3.medium

  KeyName:
    Description: EC2 Key Pair for SSH access
    Type: AWS::EC2::KeyPair::KeyName

Resources:

  # VPC
  # MyVPC:
  #   Type: 'AWS::EC2::VPC'
  #   Properties:
  #     CidrBlock: !Ref VpcCidr
  #     EnableDnsSupport: true
  #     EnableDnsHostnames: true
  #     Tags:
  #       - Key: Name
  #         Value: !Ref VPCName

  # Public Subnet
  # MyPublicSubnet:
  #   Type: 'AWS::EC2::Subnet'
  #   Properties:
  #     VpcId: !Ref MyVPC
  #     CidrBlock: !Ref PublicSubnetCidr
  #     AvailabilityZone: !Select [ 0, !GetAZs 'us-west-2' ]
  #     MapPublicIpOnLaunch: true
  #     Tags:
  #       - Key: Name
  #         Value: !Ref PublicSubnetName

  # Internet Gateway
  MyInternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties: {}
  
  # Attach Internet Gateway to VPC
  AttachGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      # VpcId: !Ref MyVPC
      InternetGatewayId: !Ref MyInternetGateway

  # Route Table for Public Subnet
  MyPublicRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      # VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: PublicRouteTable

  # Route for Internet Access
  PublicRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !Ref MyPublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MyInternetGateway

  # Associate Public Subnet with Route Table
  # PublicSubnetRouteTableAssociation:
  #   Type: 'AWS::EC2::SubnetRouteTableAssociation'
  #   Properties:
  #     SubnetId: !Ref MyPublicSubnet
  #     RouteTableId: !Ref MyPublicRouteTable

  # EC2 Instance for EKS Distro
  MyEKSInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-0c55b159cbfafe1fe  # Replace with the latest EKS Distro AMI ID
      # SubnetId: !Ref MyPublicSubnet
      Tags:
        - Key: Name
          Value: EKS-Distro-Node

# Outputs:
#   VPCId:
#     Description: The ID of the created VPC
#     Value: !Ref MyVPC

#   PublicSubnetId:
#     Description: The ID of the created public subnet
#     Value: !Ref MyPublicSubnet

#   InstanceId:
#     Description: The ID of the EC2 instance for EKS Distro
#     Value: !Ref MyEKSInstance
