AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template to create resources for AWS Snowball

Parameters:
  BucketName:
    Description: The name of the S3 bucket (must be globally unique)
    Type: String

Resources:

  # S3 Bucket for Snowball
  SnowballBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled  # Enable versioning for better data management

  # IAM Role for Snowball
  SnowballRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: snowball.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SnowballPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                # Resource:
                #   - !Sub '${SnowballBucket.Arn}'
                #   - !Sub '${SnowballBucket.Arn}/*'

# Outputs:
#   SnowballBucketArn:
#     Description: The ARN of the created S3 bucket
#     Value: !GetAtt SnowballBucket.Arn

#   SnowballRoleArn:
#     Description: The ARN of the Snowball IAM role
#     Value: !GetAtt SnowballRole.Arn
