AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template to create an Amazon FSx for OpenZFS file system

Parameters:
  FileSystemName:
    Description: The name of the FSx for OpenZFS file system
    Type: String
    Default: MyOpenZFSFileSystem

  StorageCapacity:
    Description: The storage capacity of the file system in GiB (minimum 100 GiB, maximum 524288 GiB)
    Type: Number
    Default: 100
    MinValue: 100
    MaxValue: 524288

  # SubnetId:
  #   Description: The ID of the subnet in which to create the file system
  #   Type: AWS::EC2::Subnet::Id

<<<<<<< HEAD
  SecurityGroupIds:
    Description: The security group IDs for the file system
    Type: List<AWS::EC2::SecurityGroup::Id>
=======
  # SecurityGroupIds:
  #   Description: The security group IDs for the file system
  #   Type: List<AWS::EC2::SecurityGroup::Id>
>>>>>>> 010ee410c3a9f9a035794a000376aa6a210a68eb

Resources:

  # Amazon FSx for OpenZFS File System
  MyOpenZFSFileSystem:
    Type: 'AWS::FSx::FileSystem'
    Properties:
      FileSystemType: OPENZFS
      StorageCapacity: !Ref StorageCapacity
      # SubnetId: !Ref SubnetId
      SecurityGroupIds: !Ref SecurityGroupIds
      OpenZFSConfiguration:
        RootVolumeConfiguration:
<<<<<<< HEAD
          # OriginSnapshotId: !Ref SnapshotId  # Optionally specify a snapshot to restore from
=======
          OriginSnapshotId: !Ref SnapshotId  # Optionally specify a snapshot to restore from
>>>>>>> 010ee410c3a9f9a035794a000376aa6a210a68eb
          DataCompressionType: NONE
          CopyTagsToSnapshots: true
          NfsExports:
            - ClientConfigurations:
                - ClientId: 0.0.0.0/0  # Allow access from all clients (adjust as necessary)
                  Options:
                    - no_root_squash
                    - rw
          Tags:
            - Key: Name
              Value: !Ref FileSystemName

# Outputs:
#   OpenZFSFileSystemId:
#     Description: The ID of the created FSx for OpenZFS file system
#     Value: !Ref MyOpenZFSFileSystem

#   OpenZFSFileSystemArn:
#     Description: The ARN of the created FSx for OpenZFS file system
#     Value: !GetAtt MyOpenZFSFileSystem.Arn
