AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template to create an EC2 Auto Scaling group

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.micro
      - m5.large
    ConstraintDescription: Must be a valid EC2 instance type.

  VPCId:
    Description: The VPC ID where the instances will be launched
    Type: AWS::EC2::VPC::Id

  SubnetIds:
    Description: The subnet IDs for the Auto Scaling group
    Type: List<AWS::EC2::Subnet::Id>

  DesiredCapacity:
    Description: Desired number of EC2 instances
    Type: Number
    Default: 2

Resources:

  # Security Group
  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: '0.0.0.0/0'  # Adjust for better security

  # Launch Configuration
  MyLaunchConfiguration:
    Type: 'AWS::AutoScaling::LaunchConfiguration'
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-0c55b159cbfafe1f0  # Replace with a valid AMI ID for your region
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref MySecurityGroup

  # Auto Scaling Group
  MyAutoScalingGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      VPCZoneIdentifier: !Ref SubnetIds
      LaunchConfigurationName: !Ref MyLaunchConfiguration
      MinSize: 1
      MaxSize: 5
      DesiredCapacity: !Ref DesiredCapacity
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Instance"
          PropagateAtLaunch: true

Outputs:
  AutoScalingGroupName:
    Description: Name of the Auto Scaling group
    Value: !Ref MyAutoScalingGroup

  LaunchConfigurationName:
    Description: Name of the launch configuration
    Value: !Ref MyLaunchConfiguration
