AWSTemplateFormatVersion: '2010-09-09'
Description: Simple NICE EnginFrame Setup

Resources:
  EnginFrameRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 'ec2.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'EnginFramePolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                # Action:
                #   - 'logs:*'  # Basic logging permissions
                # Resource: '*'

  EnginFrameInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    # Properties:
    #   Roles:
    #     - !Ref EnginFrameRole

  EnginFrameInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 't3.medium'  # Choose an appropriate instance type
      # ImageId: !Ref LatestAmiId
      # IamInstanceProfile: !Ref EnginFrameInstanceProfile
      # SecurityGroupIds:
      #   - !Ref EnginFrameSecurityGroup
      # SubnetId: !Ref SubnetId
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          # Placeholder for EnginFrame setup
          echo "Setting up NICE EnginFrame..."

  EnginFrameSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: "NICE EnginFrame Security Group"
      # VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 8080
          ToPort: 8080
          CidrIp: "0.0.0.0/0"  # Adjust based on security needs

Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2-ami-kernel-default-x86_64-gp2'

#   SubnetId:
#     Type: String
#     Description: 'Subnet ID for the instance'

#   VpcId:
#     Type: String
#     Description: 'VPC ID for the instance'

# Outputs:
#   InstanceId:
#     Description: 'The Instance ID of the NICE EnginFrame Instance'
#     Value: !Ref EnginFrameInstance
