AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template to create Amazon S3 on AWS Outposts

Parameters:
  OutpostId:
    Description: The ID of the Outpost where the S3 bucket will be created
    Type: String

  BucketName:
    Description: The name of the S3 bucket
    Type: String

Resources:

  # S3 Bucket on Outposts
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      OutpostId: !Ref OutpostId

# Outputs:
#   S3BucketName:
#     Description: The name of the created S3 bucket
#     Value: !Ref MyS3Bucket

#   S3BucketArn:
#     Description: The ARN of the created S3 bucket
#     Value: !GetAtt MyS3Bucket.Arn
