AWSTemplateFormatVersion: '2010-09-09'
Description: Simple Setup for AWS Outposts Server

Resources:
  OutpostInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    # Properties:
    #   Roles:
    #     - !Ref OutpostRole

  OutpostRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 'ec2.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'OutpostPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                # Action:
                #   - 'logs:*'  # Basic logging permissions
                # Resource: '*'

  OutpostSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: "Outposts Security Group"
      VpcId: !Ref OutpostVpcId
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"  # Adjust based on security needs

  OutpostInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 'c5.large'  # Choose an appropriate instance type
      # ImageId: !Ref LatestAmiId
      # IamInstanceProfile: !Ref OutpostInstanceProfile
      # SecurityGroupIds:
      #   - !Ref OutpostSecurityGroup
      # SubnetId: !Ref OutpostSubnetId
      # OutpostArn: !Ref OutpostArn
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          echo "Setting up instance on AWS Outposts..."

# Parameters:
#   LatestAmiId:
#     Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
#     Default: '/aws/service/ami-amazon-linux-latest/al2-ami-kernel-default-x86_64-gp2'

#   OutpostArn:
#     Type: String
#     Description: 'ARN of the AWS Outpost'

#   OutpostSubnetId:
#     Type: String
#     Description: 'Subnet ID for the Outpost instance'

#   OutpostVpcId:
#     Type: String
#     Description: 'VPC ID for the Outpost instance'

# Outputs:
#   InstanceId:
#     Description: 'The Instance ID of the Outpost Instance'
#     Value: !Ref OutpostInstance
