AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for AWS Direct Connect with Transit Gateway setup

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-vpc

  DirectConnectGateway:
    Type: AWS::DirectConnect::Gateway
    Properties:
      Name: !Sub ${AWS::StackName}-dx-gateway
      AmazonSideAsn: 65001

  TransitGateway:
    Type: AWS::EC2::TransitGateway
    Properties:
      AmazonSideAsn: 64512
      AutoAcceptSharedAttachments: enable
      DefaultRouteTableAssociation: enable
      DefaultRouteTablePropagation: enable
      Description: Transit Gateway for Direct Connect integration
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-tgw

  TransitGatewayAttachment:
    Type: AWS::EC2::TransitGatewayAttachment
    Properties:
      TransitGatewayId: !Ref TransitGateway
      VpcId: !Ref VPC
      SubnetIds: !Ref TransitGatewaySubnets
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-tgw-attachment

  DirectConnectGatewayAssociation:
    Type: AWS::DirectConnect::GatewayAssociation
    Properties:
      DirectConnectGatewayId: !Ref DirectConnectGateway
      GatewayId: !Ref TransitGateway
      AllowedPrefixes:
        - 10.0.0.0/16
        - 172.24.72.0/24

Parameters:
  TransitGatewaySubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Select at least 2 subnets for Transit Gateway attachment