Parameters:
  ClusterNameFor$$1:
    Type: String
    Default: $$1
    Description: "The name of the EMR cluster."

  InstanceTypeFor$$1:
    Type: String
    Default: "m5.xlarge"
    Description: "EC2 instance type for EMR core and task nodes."

  NumberOfCoreNodesFor$$1:
    Type: Number
    Default: 2
    Description: "Number of core nodes in the cluster."

Resources:
  $$1:
    Type: AWS::EMR::Cluster
    Properties:
      Name: !Ref ClusterNameFor$$1
      ReleaseLabel: "emr-6.13.0" # Adjust as per the required version
      Applications:
        - Name: "Hadoop"
        - Name: "Spark"
      Instances:
        MasterInstanceGroup:
          InstanceCount: 1
          InstanceType: !Ref InstanceTypeFor$$1
          Name: "MasterNode"
        CoreInstanceGroup:
          InstanceCount: !Ref NumberOfCoreNodesFor$$1
          InstanceType: !Ref InstanceTypeFor$$1
          Name: "CoreNode"
        Ec2SubnetId: !Ref $$2
      JobFlowRole: !Ref $$3
      ServiceRole: !Ref $$4
      Configurations:
        - Classification: "spark"
          ConfigurationProperties:
            "maximizeResourceAllocation": "true"

Outputs:
  ClusterIdFor$$1:
    Description: "EMR Cluster ID for $$1"
    Value: !Ref $$1

  ClusterEndpointFor$$1:
    Description: "Cluster Master Public DNS for $$1"
    Value: !GetAtt $$1.MasterPublicDNS

Dependencies:
["AWS::EC2::Subnet", "AWS::IAM::InstanceProfile", "AWS::IAM::RoleForEMRService"]