Resources:
  $$1:
    Type: AWS::KMS::Key
    Properties:
      Description: 'KMS key for CloudTrail log encryption for $$1'
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: kms:*
            Resource: '*'
          - Sid: Allow CloudTrail to encrypt logs
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: 
              - kms:GenerateDataKey*
              - kms:Decrypt
            Resource: '*'
Outputs:
  CloudTrailKMSKeyArnFor$$1:
    Description: 'The ARN of the KMS key used for encrypting CloudTrail logs for $$1'
    Value: !GetAtt $$1.Arn
    Export:
      Name: !Sub '${AWS::StackName}-KMSKeyArn'