Parameters:
  StreamNameFor$$1:
    Type: String
    Default: "$$1"
    Description: "The name of the Kinesis Data Stream for $$1."

  ShardCountFor$$1:
    Type: Number
    Default: 1
    Description: "The number of shards for the Kinesis Data Stream for $$1."

  RetentionHoursFor$$1:
    Type: Number
    Default: 24
    AllowedValues:
      - 24
      - 48
      - 72
      - 168
      - 8760
    Description: "Retention period for data in the stream (in hours) for $$1."

Resources:
  $$1:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Ref StreamNameFor$$1
      ShardCount: !Ref ShardCountFor$$1
      RetentionPeriodHours: !Ref RetentionHoursFor$$1
      StreamEncryption:
        EncryptionType: "KMS"
        KeyId: "alias/aws/kinesis"  # Default KMS key provided by AWS

Outputs:
  StreamArnFor$$1:
    Description: "The ARN of the Kinesis Data Stream For $$1"
    Value: !GetAtt $$1.Arn

  StreamNameFor$$1:
    Description: "The name of the Kinesis Data Stream For $$1"
    Value: !Ref $$1
