Resources:
  $$1:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt $$2.ApiId
      Definition: |
        type Query {
          getItem(id: ID!): Item
        }
        type Mutation {
          putItem(id: ID!, name: String!): Item
        }
        type Item {
          id: ID!
          name: String
        }
        schema {
          query: Query
          mutation: Mutation
        }
Dependencies:
["AWS::AppSync::GraphQLApi"]