Parameters:
  BotNameFor$$1:
    Type: String
    Default: "$$1"
    Description: "The name of the Amazon Lex bot for $$1."

  LocaleFor$$1:
    Type: String
    Default: "en_US"
    AllowedValues: 
      - en_US
      - en_GB
      - de_DE
      - es_US
      - fr_FR
    Description: "The locale for the Lex Bot (e.g., en_US for US English) for $$1."

Resources:
  $$1:
    Type: AWS::Lex::Bot
    Properties:
      Name: !Ref BotNameFor$$1
      RoleArn: !GetAtt $$2.Arn
      DataPrivacy:
        ChildDirected: false
      IdleSessionTTLInSeconds: 300
      BotLocales:
        - LocaleId: !Ref LocaleFor$$1
          Description: !Sub "Sample bot for ${LocaleFor$$1}"
          VoiceSettings:
            VoiceId: "Joanna"
          NluConfidenceThreshold: 0.8
          Intents:
            - Name: "SampleIntent"
              SampleUtterances:
                - Utterance: "What is the weather like in {Location}?"
                - Utterance: "Tell me the forecast for {Location}"
              Slots:
                - Name: "Location"
                  SlotTypeName: "AMAZON.City"
                  ValueElicitationSetting:
                    SlotConstraint: Required
                    PromptSpecification:
                      MaxRetries: 2
                      MessageGroupsList:
                        - Message:
                            PlainTextMessage:
                              Value: "Which city are you asking about?"

Outputs:
  LexBotIdFor$$1:
    Description: "The ID of the Lex Bot for $$1."
    Value: !Ref $$1

Dependencies:
["AWS::IAM::RoleForLexExecution"]