Parameters:
  HostedZoneIdFor$$1:
    Type: String
    Description: The Route 53 Hosted Zone ID for your domain for $$1
Resources:
  $$1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneIdFor$$1
      Name: !Ref DomainNameFor$$2
      Type: A
      AliasTarget:
        DNSName: !GetAtt $$2.RegionalDomainName
        HostedZoneId: !GetAtt $$2.RegionalHostedZoneId
Dependencies:
["AWS::ApiGateway::DomainName"]