Parameters:
  ClusterNameFor$$1:
    Type: String
    Description: Name of the EKS cluster for $$1
    Default: $$1

  KubernetesVersionFor$$1:
    Type: String
    Description: Kubernetes version for the EKS cluster for $$1
    Default: 1.27

Resources:
  $$1:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref ClusterNameFor$$1
      Version: !Ref KubernetesVersionFor$$1
      RoleArn: !GetAtt $$2.Arn
      ResourcesVpcConfig:
        SubnetIds: !Ref $$2

Outputs:
  ClusterNameFor$$1:
    Description: EKS Cluster Name for $$1
    Value: !Ref $$1
  ClusterEndpointFor$$1:
    Description: EKS Cluster Endpoint for $$1
    Value: !GetAtt $$1.Endpoint
  ClusterARNFor$$1:
    Description: EKS Cluster ARN for $$1
    Value: !GetAtt $$1.Arn

Dependencies:
["AWS::EC2::Subnet", "AWS::IAM::RoleForEKSCluster"]