Parameters:  
  RuleNameFor$$1:
    Type: String
    Default: "$$1"
    Description: "Name of the EventBridge Rule for $$1"

Resources:
  $$1:
    Type: "AWS::Events::Rule"
    Properties:
      Name: !Ref RuleNameFor$$1
      Description: "Rule to trigger Lambda on specific event patterns for $$1"
      EventBusName: !Ref $$2
      EventPattern:
        source:
          - "aws.s3"
        detail-type:
          - "AWS API Call via CloudTrail"
        detail:
          eventSource:
            - "s3.amazonaws.com"
          eventName:
            - "PutObject"
          resources:
            - !Sub "arn:aws:s3:::${$$4}"
      State: "ENABLED"
      Targets:
        - Id: "LambdaTarget"
          Arn: !GetAtt $$3.Arn

Dependencies:
["AWS::Events::EventBus", "AWS::Lambda::Function", "AWS::S3::Bucket"]

Disclaimers:
["The Amazon S3 bucket $$4's events (e.g., PutObject) will trigger this rule."]