Parameters:
  EnvironmentFor$$1:
    Type: String
    Default: dev
    AllowedValues: 
      - dev
      - staging
      - prod
    Description: 'Environment name for resource tagging for $$1'
Resources:
  $$1:
    Type: AWS::CloudTrail::Trail
    DependsOn: 
      - $$3
    Properties:
      TrailName: !Sub '${EnvironmentFor$$1}-cloudtrail'
      S3BucketName: !Ref $$2
      IsMultiRegionTrail: true
      EnableLogFileValidation: true
      IncludeGlobalServiceEvents: true
      IsLogging: true
      KMSKeyId: !GetAtt $$4.Arn
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentFor$$1
Outputs:
  CloudTrailArnFor$$1:
    Description: 'The ARN of the CloudTrail for $$1'
    Value: !GetAtt $$1.Arn
    Export:
      Name: !Sub '${AWS::StackName}-CloudTrailArn'
Dependencies:
["AWS::S3::Bucket", "AWS::S3::BucketPolicy", "AWS::KMS::Key"]