Parameters:
  CacheNodeTypeFor$$1:
    Type: String
    Default: 'cache.t3.micro'
    Description: 'The compute and memory capacity of the nodes for $$1'

  EngineVersionFor$$1:
    Type: String
    Default: '6.x'
    Description: 'The version number of the cache engine for $$1'

  NumCacheNodesFor$$1:
    Type: Number
    Default: 1
    Description: 'The number of cache nodes in the cluster for $$1'
Resources:
  $$1:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      Engine: redis
      CacheNodeType: !Ref CacheNodeTypeFor$$1
      NumCacheNodes: !Ref NumCacheNodesFor$$1
      EngineVersion: !Ref EngineVersionFor$$1
      ClusterName: $$1
      Port: 6379
      CacheParameterGroupName: default.redis6.x
Outputs:
  ElastiCacheEndpointFor$$1:
    Description: 'ElastiCache Endpoint for $$1'
    Value: !GetAtt $$1.RedisEndpoint.Address