Parameters:
  AlarmThresholdFor$$1:
    Type: Number
    Default: 70
    Description: "The CPU utilization percentage threshold to trigger the alarm for $$1"

Resources:
  $$1:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: HighCPUAlarm$$1
      AlarmDescription: Alarm if CPU exceeds the specified threshold for $$1
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: !Ref AlarmThresholdFor$$1
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: InstanceId
          Value: !Ref InstanceIdFor$$2
      AlarmActions:
        - !Ref $$3
Outputs:
  AlarmNameFor$$1:
    Description: 'Name of the CloudWatch Alarm for $$1'
    Value: !Ref $$1
Dependencies:
["AWS::CloudWatch::Dashboard", "AWS::SNS::Topic"]