Resources:
  $$1:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - transcribe.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: TranscribePermissionsFor$$1
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - transcribe:StartTranscriptionJob
                  - transcribe:GetTranscriptionJob
                  - transcribe:ListTranscriptionJobs
                  - transcribe:DeleteTranscriptionJob
                  - sns:Publish
                Resource: "*"
Outputs:
  TranscribeRoleArnFor$$1:
    Description: IAM Role ARN for Transcribe permissions for $$1.
    Value: !GetAtt $$1.Arn