Parameters:
  ListenerPortFor$$1:
    Type: Number
    Default: 80
    Description: Port number for the VPC Lattice Listener for $$1
Resources:
  $$1:
    Type: AWS::VpcLattice::Listener
    Properties:
      Name: !Sub "${LatticeServiceNameFor$$2}-listener"
      Protocol: HTTP
      Port: !Ref ListenerPortFor$$1
      DefaultAction:
        Forward:
          TargetGroups:
            - TargetGroupIdentifier: !Ref $$3
      ServiceIdentifier: !Ref $$2
Outputs:
  LatticeListenerIdFor$$1:
    Description: ID of the VPC Lattice Listener for $$1
    Value: !Ref $$1
Dependencies:
["AWS::VpcLattice::Service", "AWS::VpcLattice::TargetGroup"]