Resources:
  $$1:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Ref $$4
      NodeRole: !GetAtt $$2.Arn
      ScalingConfig:
        MinSize: 1
        DesiredSize: 3
        MaxSize: 5
      Subnets: !Ref $$3

Dependencies:
["AWS::IAM::RoleForEKSNodeGroup", "AWS::EC2::Subnet", "AWS::EKS::Cluster"]