Parameters:
  ApiKeyExpiryFor$$1:
    Type: Number
    Description: "Unix timestamp when the API key should expire for $$1."
    Default: 1700889600

Resources:
  $$1:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId: !GetAtt $$2.ApiId
      Expires: !Ref ApiKeyExpiryFor$$1
Outputs:
  ApiKeyFor$$1:
    Description: "The API key for accessing the AppSync API for $$1"
    Value: !Ref $$1
Dependencies:
["AWS::AppSync::GraphQLApi"]