Parameters:
  DBInstanceClassFor$$1:
    Description: The compute and memory capacity of the DB instance for $$1
    Type: String
    Default: db.t3.micro
    AllowedValues:
      - db.t3.micro
      - db.t3.small
      - db.t3.medium
      - db.t3.large
    ConstraintDescription: Must be a valid DB instance class.
  DBEngineFor$$1:
    Description: The database engine to use
    Type: String
    Default: MySQL
    AllowedValues:
      - MySQL
      - aurora-postgresql
      - sqlserver-express
      - oracle-se2  
    ConstraintDescription: Must be a valid database engine.
  DBNameFor$$1:
    Description: The name of the database to create for $$1
    Type: String
    Default: mydatabaseFor$$1
  MasterUsernameFor$$1:
    Description: The master username for the database for $$1
    Type: String
    Default: admin
Resources:
  $$1:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceIdentifierFor$$2
      DBInstanceClass: !Ref DBInstanceClassFor$$1
      Engine: !Ref DBEngineFor$$1
      DBName: !Ref DBNameFor$$1
      MasterUsername: !Ref MasterUsernameFor$$1
      MasterUserPassword: '{{resolve:secretsmanager:RDS-database-password:SecretString:password}}'
      DBSubnetGroupName: !Ref $$2
      AllocatedStorage: '20'
      StorageType: gp2
Outputs:
  DBInstanceEndpointFor$$1:
    Description: The endpoint of the RDS database instance for $$1
    Value: !GetAtt $$1.Endpoint.Address
Dependencies:
["AWS::RDS::DBSubnetGroup"]
Disclaimers:
["Assumes the master password is stored in AWS Secrets Manager with the secret name RDS-database-password"]