Parameters:
  ExecutionRoleNameFor$$1:
    Type: String
    Default: "$$1"
    Description: "The name of the IAM role for the SageMaker Notebook Instance for $$1."

Resources:
  $$1:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref ExecutionRoleNameFor$$1
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: "SageMakerNotebookPolicyFor$$1"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetObject
                  - s3:PutObject
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - sagemaker:*
                Resource: "*"
Outputs:
  ExecutionRoleArnFor$$1:
    Description: "The ARN of the SageMaker Notebook execution role for $$1."
    Value: !GetAtt $$1.Arn