Resources:
  $$1:
    Type: AWS::ApiGateway::VpcLink
    Properties:
      Name: !Sub "${$$2}-VpcLink"
      TargetArns:
        - !Ref $$3
Outputs:
  VpcLinkIdFor$$1:
    Description: ID of the VPC Link for $$1
    Value: !Ref $$1
Dependencies:
["AWS::ApiGateway::RestApi", "AWS::VpcLattice::ServiceNetwork"]