Parameters:
  StateMachineNameFor$$1:
    Type: String
    Default: "$$1"
    Description: "The name of the Step Functions state machine for $$1."

Resources:
  $$1:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Ref StateMachineNameFor$$1
      RoleArn: !GetAtt $$3.Arn
      DefinitionString: !Sub |
        {
          "Comment": "A simple AWS Step Functions example for $$1",
          "StartAt": "InvokeLambda",
          "States": {
            "InvokeLambda": {
              "Type": "Task",
              "Resource": "${$$2.Arn}",
              "End": true
            }
          }
        }

Outputs:
  StateMachineArnFor$$1:
    Description: "The ARN of the Step Functions state machine for $$1."
    Value: !Ref $$1

Dependencies:
["AWS::Lambda::Function", "AWS::IAM::RoleForStepFunctionExecution"]