Parameters:
  ContainerImageFor$$1:
    Type: String
    Description: Docker image for the container for $$1
    Default: nginx:latest

  ContainerPortFor$$1:
    Type: Number
    Description: Port exposed by the container for $$1
    Default: 80

Resources:
  $$1:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: fargate-task
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Name: fargate-app-$$1
          Image: !Ref ContainerImageFor$$1
          PortMappings:
            - ContainerPort: !Ref ContainerPortFor$$1