
Resources:
  $$1:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-postgresql
      EngineVersion: 13.7
      DatabaseName: !Ref DBNameFor$$2
      MasterUsername: !Ref MasterUsernameFor$$2
      MasterUserPassword: '{{resolve:secretsmanager:RDS-database-password:SecretString:password}}'
      DBSubnetGroupName: !Ref $$3
Outputs:
  ClusterEndpointFor$$1:
    Description: The connection endpoint for the database for $$1
    Value: !GetAtt $$1.Endpoint.Address
  ReadEndpointFor$$1:
    Description: The reader endpoint for the database for $$1
    Value: !GetAtt $$1.ReadEndpoint.Address

Dependencies:
["AWS::RDS::DBInstanceForCluster", "AWS::RDS::DBSubnetGroup"]