Parameters:
  CrawlerScheduleFor$$1:
    Type: String
    Default: "cron(0 12 * * ? *)"
    Description: Cron expression for crawler schedule for $$1

Resources:
  $$1:
    Type: "AWS::Glue::Crawler"
    Properties:
      Role: !GetAtt $$2.Arn
      DatabaseName: !Ref $$3
      Name: !Sub "${DatabaseNameFor$$3}-crawler"
      Description: "Crawler to populate the Glue database."
      Targets:
        S3Targets:
          - Path: !Sub "s3://${$$4}/data/"
      Schedule: 
        ScheduleExpression: !Ref CrawlerScheduleFor$$1

Outputs:
  GlueCrawlerNameFor$$1:
    Description: "The name of the Glue crawler for $$1"
    Value: !Ref $$1

Dependencies:
["AWS::IAM::RoleForGlueService", "AWS::Glue::Database", "AWS::S3::Bucket"]

Disclaimers:
["The crawler $$1 will scan for data in the S3 location /data/ inside the S3 bucket $$4"]