Parameters:
  MinSizeFor$$1:
    Type: Number
    Default: 1
    MinValue: 0
    MaxValue: 10
    Description: 'Minimum size of the Auto Scaling group for $$1'

  MaxSizeFor$$1:
    Type: Number
    Default: 3
    MinValue: 1
    MaxValue: 10
    Description: 'Maximum size of the Auto Scaling group for $$1'

  DesiredCapacityFor$$1:
    Type: Number
    Default: 2
    MinValue: 1
    MaxValue: 10
    Description: 'Desired capacity of the Auto Scaling group for $$1'
Resources:
  $$1:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref $$2
        Version: !GetAtt $$2.LatestVersionNumber
      MinSize: !Ref MinSizeFor$$1
      MaxSize: !Ref MaxSizeFor$$1
      DesiredCapacity: !Ref DesiredCapacityFor$$1
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300
      VPCZoneIdentifier: 
        - !Ref $$3
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-asg'
          PropagateAtLaunch: true
        - Key: Environment
          Value: !Ref EnvironmentFor$$2
          PropagateAtLaunch: true
Outputs:
  AutoScalingGroupNameFor$$1:
    Description: 'Auto Scaling Group Name for $$1'
    Value: !Ref $$1
    Export:
      Name: !Sub '${AWS::StackName}-asg-name'
Dependencies:
["AWS::EC2::LaunchTemplate", "AWS::EC2::Subnet"]