Parameters:
  NotebookInstanceNameFor$$1:
    Type: String
    Default: "$$1"
    Description: "The name of the SageMaker Notebook Instance for $$1."

  NotebookInstanceTypeFor$$1:
    Type: String
    Default: "ml.t2.medium"
    AllowedValues:
      - "ml.t2.medium"
      - "ml.m5.large"
      - "ml.m5.xlarge"
      - "ml.c5.large"
      - "ml.c5.xlarge"
    Description: "The instance type for the SageMaker Notebook Instance for $$1."

  RootAccessFor$$1:
    Type: String
    Default: "Disabled"
    AllowedValues:
      - "Enabled"
      - "Disabled"
    Description: "Whether the SageMaker Notebook Instance has root access for $$1."

Resources:
  $$1:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      NotebookInstanceName: !Ref NotebookInstanceNameFor$$1
      InstanceType: !Ref NotebookInstanceTypeFor$$1
      RoleArn: !GetAtt $$2.Arn
      RootAccess: !Ref RootAccessFor$$1
      VolumeSizeInGB: 10 # Adjust the volume size as needed
      DirectInternetAccess: "Enabled"
Outputs:
  NotebookInstanceNameFor$$1:
    Description: "The name of the SageMaker Notebook Instance for $$1."
    Value: !Ref $$1

  NotebookInstanceUrlFor$$1:
    Description: "The URL to access the SageMaker Notebook Instance."
    Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/sagemaker/home?region=${AWS::Region}#/notebook-instances/openNotebook/${NotebookInstanceNameFor$$1}"
Dependencies:
["AWS::IAM::RoleForSageMakerExecution"]
Disclaimers:
["This template assumes development of machine learning workflows as the usecase."]