Parameters:
  DomainNameFor$$1:
    Type: String
    Default: "MyOpenSearchDomain"
    Description: "The name of the OpenSearch domain for $$1."

  InstanceTypeFor$$1:
    Type: String
    Default: "m6g.large.search"
    Description: "The instance type for the data nodes in the OpenSearch cluster for $$1."

  InstanceCountFor$$1:
    Type: Number
    Default: 2
    Description: "The number of data nodes in the OpenSearch cluster for $$1."

  MasterInstanceTypeFor$$1:
    Type: String
    Default: "m6g.medium.search"
    Description: "The instance type for the dedicated master nodes for $$1."

  MasterInstanceCountFor$$1:
    Type: Number
    Default: 3
    Description: "The number of dedicated master nodes in the OpenSearch cluster for $$1."

  VolumeSizeFor$$1:
    Type: Number
    Default: 10
    Description: "The size (in GB) of the EBS volumes attached to each data node for $$1."

Resources:
  $$1:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: !Ref DomainNameFor$$1
      EngineVersion: "OpenSearch_2.9"
      ClusterConfig:
        InstanceType: !Ref InstanceTypeFor$$1
        InstanceCount: !Ref InstanceCountFor$$1
        DedicatedMasterEnabled: true
        ZoneAwarenessEnabled: true
        DedicatedMasterType: !Ref MasterInstanceTypeFor$$1
        DedicatedMasterCount: !Ref MasterInstanceCountFor$$1
      EBSOptions:
        EBSEnabled: true
        VolumeSize: !Ref VolumeSizeFor$$1
        VolumeType: "gp3"
      VPCOptions:
        SubnetIds: !Ref $$2
      EncryptionAtRestOptions:
        Enabled: true
      NodeToNodeEncryptionOptions:
        Enabled: true
      DomainEndpointOptions:
        EnforceHTTPS: true
      AdvancedOptions:
        "rest.action.multi.allow_explicit_index": "true"
      LogPublishingOptions:
        SEARCH_SLOW_LOGS:
          CloudWatchLogsLogGroupArn: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/OpenSearch/${DomainNameFor$$1}-search-slow"
          Enabled: true
        INDEX_SLOW_LOGS:
          CloudWatchLogsLogGroupArn: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/OpenSearch/${DomainNameFor$$1}-index-slow"
          Enabled: true
        ES_APPLICATION_LOGS:
          CloudWatchLogsLogGroupArn: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/OpenSearch/${DomainNameFor$$1}-app-logs"
          Enabled: true

Outputs:
  OpenSearchDomainArnFor$$1:
    Description: "The ARN of the OpenSearch Domain"
    Value: !GetAtt $$1.Arn

  OpenSearchDomainEndpointFor$$1:
    Description: "The endpoint of the OpenSearch Domain"
    Value: !GetAtt $$1.DomainEndpoint
  
Dependencies:
["AWS::EC2::Subnet"]
