Parameters:
  SourceEndpointArnFor$$1:
    Type: String
    Description: 'The ARN of the source endpoint for $$1'

  TargetEndpointArnFor$$1:
    Type: String
    Description: 'The ARN of the target endpoint for $$1'

Resources:
  $$1:
    Type: AWS::DMS::ReplicationTask
    Properties:
      MigrationType: 'full-load-and-cdc'
      ReplicationInstanceArn: !Ref $$2
      SourceEndpointArn: !Ref SourceEndpointArnFor$$1
      TargetEndpointArn: !Ref TargetEndpointArnFor$$1
      TableMappings: '{"rules": [{"rule-type": "selection", "rule-id": "1", "rule-name": "1", "object-locator": {"schema-name": "%", "table-name": "%"}, "rule-action": "include"}]}'
Outputs:
  ReplicationTaskArnFor$$1:
    Description: 'ARN of the DMS Replication Task for $$1'
    Value: !Ref $$1
Dependencies:
["AWS::DMS::ReplicationInstance"]