Parameters:
  BrokerNameFor$$1:
    Type: String
    Default: "$$1"
    Description: "The name of the Amazon MQ broker for $$1."

  BrokerInstanceTypeFor$$1:
    Type: String
    Default: "mq.t3.micro"
    AllowedValues:
      - "mq.t3.micro"
      - "mq.m5.large"
    Description: "The broker instance type for $$1."

  DeploymentModeFor$$1:
    Type: String
    Default: "SINGLE_INSTANCE"
    AllowedValues:
      - "SINGLE_INSTANCE"
      - "ACTIVE_STANDBY_MULTI_AZ"
    Description: "The deployment mode for the Amazon MQ broker for $$1."

  EngineTypeFor$$1:
    Type: String
    Default: "ACTIVEMQ"
    AllowedValues:
      - "ACTIVEMQ"
      - "RABBITMQ"
    Description: "The message broker engine type for $$1."

  EngineVersionFor$$1:
    Type: String
    Default: "5.17.1"
    Description: "The version of the broker engine for $$1."

  SecretNameFor$$1:
    Type: String
    Default: "/$$1/mq-password"
    Description: "The name of the secret storing the MQ broker password for $$1."

Resources:
  $$1:
    Type: "AWS::AmazonMQ::Broker"
    Properties:
      BrokerName: !Ref BrokerNameFor$$1
      DeploymentMode: !Ref DeploymentModeFor$$1
      EngineType: !Ref EngineTypeFor$$1
      EngineVersion: !Ref EngineVersionFor$$1
      HostInstanceType: !Ref BrokerInstanceTypeFor$$1
      SubnetIds: !Ref $$2
      Users:
        - Username: "admin"
          Password: !Sub "{{resolve:secretsmanager:${SecretNameFor$$1}:SecretString:password}}"
      PubliclyAccessible: false
      AutoMinorVersionUpgrade: true

Outputs:
  BrokerNameOutputFor$$1:
    Description: "The name of the Amazon MQ broker for $$1."
    Value: !Ref BrokerNameFor$$1

  BrokerEndpointOutputFor$$1:
    Description: "The endpoint for connecting to the Amazon MQ broker for $$1."
    Value: !GetAtt $$1.Arn

Dependencies:
["AWS::EC2::Subnet"]

Disclaimers:
["Fetches the password securely from SSM Parameter Store."]