Parameters:
  EnvironmentNameFor$$1:
    Type: String
    Default: "$$1"
    Description: "The name of the MWAA environment for $$1"

  AirflowVersionFor$$1:
    Type: String
    Default: "2.6.3"
    AllowedValues:
      - "2.2.2"
      - "2.4.3"
      - "2.5.1"
      - "2.6.3"
    Description: "Apache Airflow version to use for the environment for $$1"

  MaxWorkersFor$$1:
    Type: Number
    Default: 2
    Description: "The maximum number of workers for the Airflow scheduler for $$1"

Resources:
  $$1:
    Type: "AWS::MWAA::Environment"
    Properties:
      Name: !Ref EnvironmentNameFor$$1
      AirflowVersion: !Ref AirflowVersionFor$$1
      EnvironmentClass: "mw1.small"
      ExecutionRoleArn: !GetAtt $$3.Arn
      MaxWorkers: !Ref MaxWorkers
      SourceBucketArn: !Sub "arn:aws:s3:::${$$2}"
      DagS3Path: "dags/"
      LoggingConfiguration:
        DagProcessingLogs:
          LogLevel: "INFO"
          Enabled: true
        SchedulerLogs:
          LogLevel: "INFO"
          Enabled: true
        TaskLogs:
          LogLevel: "INFO"
          Enabled: true
        WebserverLogs:
          LogLevel: "INFO"
          Enabled: true
        WorkerLogs:
          LogLevel: "INFO"
          Enabled: true
      WebserverAccessMode: "PUBLIC_ONLY"

Outputs:
  EnvironmentNameOutputFor$$1:
    Description: "The name of the MWAA environment for $$1"
    Value: !Ref EnvironmentNameFor$$1

Dependencies:
["AWS::S3::Bucket", "AWS::IAM::RoleForMWAA"]

Disclaimers:
["DAGs should be stored in the 'dags/' folder of the bucket $$2"]