AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Template for a60e585f-27be-4dd6-897b-c38adf1d283f.png
Conditions: 



Parameters: 
  QueueNameForMyQueue1:
    Type: String
    Default: "MyQueue1"
    Description: "The name of the SQS queue for MyQueue1."
  VisibilityTimeoutForMyQueue1:
    Type: Number
    Default: 30
    MinValue: 0
    MaxValue: 43200
    Description: "The visibility timeout for the queue in seconds for MyQueue1."
  MessageRetentionPeriodForMyQueue1:
    Type: Number
    Default: 345600  # 4 days
    MinValue: 60
    MaxValue: 1209600  # 14 days
    Description: "The number of seconds for which Amazon SQS retains a message for MyQueue1."

  ClusterNameForMyFargateCluster1:
    Description: The name of the ECS cluster
    Type: String
    Default: MyFargateCluster1
  StreamNameForMyStream1:
    Type: String
    Default: "MyStream1"
    Description: "The name of the Kinesis Data Stream for MyStream1."
  ShardCountForMyStream1:
    Type: Number
    Default: 1
    Description: "The number of shards for the Kinesis Data Stream for MyStream1."
  RetentionHoursForMyStream1:
    Type: Number
    Default: 24
    AllowedValues:
      - 24
      - 48
      - 72
      - 168
      - 8760
    Description: "Retention period for data in the stream (in hours) for MyStream1."

  ContainerImageForMyTaskDefinitionFargate1:
    Type: String
    Description: Docker image for the container for MyTaskDefinitionFargate1
    Default: nginx:latest
  ContainerPortForMyTaskDefinitionFargate1:
    Type: Number
    Description: Port exposed by the container for MyTaskDefinitionFargate1
    Default: 80

  ClusterNameForMyCluster1:
    Description: The name of the ECS cluster
    Type: String
    Default: MyCluster1
  VPCCidrBlockForMyVPC1:
    Description: The CIDR block for the VPC
    Type: String
    Default: 10.0.0.0/16
    AllowedPattern: '^(([0-9]{1,3})\.){3}[0-9]{1,3}/([0-9]|[1-2][0-9]|3[0-2])$'
    ConstraintDescription: Must be a valid CIDR block.
  SubnetCidrBlockForMySubnet1:
    Description: The CIDR block for the new subnet
    Type: String
    Default: 10.0.1.0/24
    AllowedPattern: '^(([0-9]{1,3})\.){3}[0-9]{1,3}/([0-9]|[1-2][0-9]|3[0-2])$'
    ConstraintDescription: Must be a valid CIDR block.
  AvailabilityZoneForMySubnet1:
    Description: The Availability Zone for the subnet
    Type: String
    Default: us-east-1a  # Replace with your desired AZ

Resources: 
  MyQueue1:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref QueueNameForMyQueue1
      VisibilityTimeout: !Ref VisibilityTimeoutForMyQueue1
      MessageRetentionPeriod: !Ref MessageRetentionPeriodForMyQueue1

  MyFargateCluster1:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: !Ref ClusterNameForMyFargateCluster1
  MyStream1:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Ref StreamNameForMyStream1
      ShardCount: !Ref ShardCountForMyStream1
      RetentionPeriodHours: !Ref RetentionHoursForMyStream1
      StreamEncryption:
        EncryptionType: "KMS"
        KeyId: "alias/aws/kinesis"  # Default KMS key provided by AWS

  MyTaskDefinitionFargate1:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: fargate-task
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Name: fargate-app-MyTaskDefinitionFargate1
          Image: !Ref ContainerImageForMyTaskDefinitionFargate1
          PortMappings:
            - ContainerPort: !Ref ContainerPortForMyTaskDefinitionFargate1
  MyCluster1:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: !Ref ClusterNameForMyCluster1
  MyVPC1:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: !Ref VPCCidrBlockForMyVPC1
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MyVPC1
  MySubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref MyVPC1
      CidrBlock: !Ref SubnetCidrBlockForMySubnet1
      AvailabilityZone: !Ref AvailabilityZoneForMySubnet1
      MapPublicIpOnLaunch: true  # Set to true if you want instances to have public IPs by default
      Tags:
        - Key: Name
          Value: MySubnet1
  MyServiceFargate1:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: MyServiceFargate1
      Cluster: !Ref MyCluster1
      TaskDefinition: !Ref MyTaskDefinitionFargate1
      DesiredCount: 2
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref MySubnet1

Outputs: 
  SQSQueueNameForMyQueue1:
    Description: "The name of the SQS queue for MyQueue1."
    Value: !Ref MyQueue1
  SQSQueueURLForMyQueue1:
    Description: "The URL of the SQS queue for MyQueue1."
    Value: !Ref MyQueue1
  SQSQueueARNForMyQueue1:
    Description: "The ARN of the SQS queue for MyQueue1."
    Value: !GetAtt MyQueue1.Arn

  ClusterNameOutputForMyFargateCluster1:
    Description: The name of the created ECS cluster for MyFargateCluster1
    Value: !Ref MyFargateCluster1
  StreamArnForMyStream1:
    Description: "The ARN of the Kinesis Data Stream For MyStream1"
    Value: !GetAtt MyStream1.Arn
  StreamNameForMyStream1:
    Description: "The name of the Kinesis Data Stream For MyStream1"
    Value: !Ref MyStream1


  ClusterNameOutputForMyCluster1:
    Description: The name of the created ECS cluster for MyCluster1
    Value: !Ref MyCluster1
  VPCId:
    Description: The ID of the created VPC for MyVPC1
    Value: !Ref MyVPC1
  SubnetId:
    Description: The ID of the created subnet for MySubnet1
    Value: !Ref MySubnet1
  ServiceNameForMyServiceFargate1:
    Description: ECS Service Name for MyServiceFargate1
    Value: !Ref MyServiceFargate1

