AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Template for describe-for-me-web-app.png
Conditions: 
  VersioningEnabledForMyBucket1: !Equals [!Ref EnableVersioningForMyBucket1, true]
  VersioningEnabledForMyBucket2: !Equals [!Ref EnableVersioningForMyBucket2, true]




Parameters: 
  BucketNameForMyBucket1:
    Description: The name of the S3 bucket
    Type: String
  EnableVersioningForMyBucket1:
    Description: Enable versioning for S3 buckets
    Type: String
    Default: false
    AllowedValues: [true, false]
  BucketNameForMyBucket2:
    Description: The name of the S3 bucket
    Type: String
  EnableVersioningForMyBucket2:
    Description: Enable versioning for S3 buckets
    Type: String
    Default: false
    AllowedValues: [true, false]

  ExecutionRoleNameForMyRoleForSageMakerExecution1:
    Type: String
    Default: "MyRoleForSageMakerExecution1"
    Description: "The name of the IAM role for the SageMaker Notebook Instance for MyRoleForSageMakerExecution1."

  NotebookInstanceNameForMyNotebookInstance1:
    Type: String
    Default: "MyNotebookInstance1"
    Description: "The name of the SageMaker Notebook Instance for MyNotebookInstance1."
  NotebookInstanceTypeForMyNotebookInstance1:
    Type: String
    Default: "ml.t2.medium"
    AllowedValues:
      - "ml.t2.medium"
      - "ml.m5.large"
      - "ml.m5.xlarge"
      - "ml.c5.large"
      - "ml.c5.xlarge"
    Description: "The instance type for the SageMaker Notebook Instance for MyNotebookInstance1."
  RootAccessForMyNotebookInstance1:
    Type: String
    Default: "Disabled"
    AllowedValues:
      - "Enabled"
      - "Disabled"
    Description: "Whether the SageMaker Notebook Instance has root access for MyNotebookInstance1."

  StateMachineNameForMyStateMachine1:
    Type: String
    Default: "MyStateMachine1"
    Description: "The name of the Step Functions state machine for MyStateMachine1."

Resources: 
  MyBucket1:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketNameForMyBucket1
      VersioningConfiguration:
        Status: !If 
          - VersioningEnabledForMyBucket1 
          - Enabled 
          - Suspended
  MyBucket2:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketNameForMyBucket2
      VersioningConfiguration:
        Status: !If 
          - VersioningEnabledForMyBucket2 
          - Enabled 
          - Suspended
  MyRoleForStepFunctionExecution1:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: "StepFunctionExecutionPolicyForMyRoleForStepFunctionExecution1"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
  MyRoleForSageMakerExecution1:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref ExecutionRoleNameForMyRoleForSageMakerExecution1
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: "SageMakerNotebookPolicyForMyRoleForSageMakerExecution1"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetObject
                  - s3:PutObject
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - sagemaker:*
                Resource: "*"

  MyRoleForLambda1:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecutionForMyRoleForLambda1
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
  MyBucketPolicy1:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref MyBucket1
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${MyBucket1.Arn}/*"
            Condition:
              Bool:
                "aws:SecureTransport": "true"
            # Example condition for allowing secure transport only
  MyBucketPolicy2:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref MyBucket2
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${MyBucket2.Arn}/*"
            Condition:
              Bool:
                "aws:SecureTransport": "true"
            # Example condition for allowing secure transport only
  MyNotebookInstance1:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      NotebookInstanceName: !Ref NotebookInstanceNameForMyNotebookInstance1
      InstanceType: !Ref NotebookInstanceTypeForMyNotebookInstance1
      RoleArn: !GetAtt MyRoleForSageMakerExecution1.Arn
      RootAccess: !Ref RootAccessForMyNotebookInstance1
      VolumeSizeInGB: 10 # Adjust the volume size as needed
      DirectInternetAccess: "Enabled"

  MyFunction1:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: MySimpleFunctionForMyFunction1
      Handler: index.handler
      Role: !GetAtt MyRoleForLambda1.Arn
      Code:
        ZipFile: |
          def handler(event, context):
            return {
              'statusCode': 200,
              'body': 'Hello, World!'
            }
      Runtime: python3.9
      Timeout: 10
  MyStateMachine1:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Ref StateMachineNameForMyStateMachine1
      RoleArn: !GetAtt MyRoleForStepFunctionExecution1.Arn
      DefinitionString: !Sub |
        {
          "Comment": "A simple AWS Step Functions example for MyStateMachine1",
          "StartAt": "InvokeLambda",
          "States": {
            "InvokeLambda": {
              "Type": "Task",
              "Resource": "${MyFunction1.Arn}",
              "End": true
            }
          }
        }

Outputs: 
  S3BucketNameForMyBucket1:
    Description: The name of the created S3 bucket for MyBucket1
    Value: !Ref MyBucket1
  S3BucketArnForMyBucket1:
    Description: The ARN of the created S3 bucket for MyBucket1
    Value: !GetAtt MyBucket1.Arn
  S3BucketNameForMyBucket2:
    Description: The name of the created S3 bucket for MyBucket2
    Value: !Ref MyBucket2
  S3BucketArnForMyBucket2:
    Description: The ARN of the created S3 bucket for MyBucket2
    Value: !GetAtt MyBucket2.Arn

  ExecutionRoleArnForMyRoleForSageMakerExecution1:
    Description: "The ARN of the SageMaker Notebook execution role for MyRoleForSageMakerExecution1."
    Value: !GetAtt MyRoleForSageMakerExecution1.Arn
  NotebookInstanceNameForMyNotebookInstance1:
    Description: "The name of the SageMaker Notebook Instance for MyNotebookInstance1."
    Value: !Ref MyNotebookInstance1
  NotebookInstanceUrlForMyNotebookInstance1:
    Description: "The URL to access the SageMaker Notebook Instance."
    Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/sagemaker/home?region=${AWS::Region}#/notebook-instances/openNotebook/${NotebookInstanceNameForMyNotebookInstance1}"

  LambdaFunctionArnForMyFunction1:
    Description: The ARN of the Lambda function for MyFunction1
    Value: !GetAtt MyFunction1.Arn
  StateMachineArnForMyStateMachine1:
    Description: "The ARN of the Step Functions state machine for MyStateMachine1."
    Value: !Ref MyStateMachine1

