AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Template for electric-vehicle-charging-station-management-software-option-1.png
Conditions: 
  VersioningEnabledForMyBucket1: !Equals [!Ref EnableVersioningForMyBucket1, true]
  VersioningEnabledForMyBucket2: !Equals [!Ref EnableVersioningForMyBucket2, true]

















Parameters: 
  BucketNameForMyBucket1:
    Description: The name of the S3 bucket
    Type: String
  EnableVersioningForMyBucket1:
    Description: Enable versioning for S3 buckets
    Type: String
    Default: false
    AllowedValues: [true, false]
  ClusterNameForMyFargateCluster1:
    Description: The name of the ECS cluster
    Type: String
    Default: MyFargateCluster1
  BucketNameForMyBucket2:
    Description: The name of the S3 bucket
    Type: String
  EnableVersioningForMyBucket2:
    Description: Enable versioning for S3 buckets
    Type: String
    Default: false
    AllowedValues: [true, false]
  ClusterNameForMyFargateCluster2:
    Description: The name of the ECS cluster
    Type: String
    Default: MyFargateCluster2
  InstanceIdForMyDashboard1:
    Type: String
    Description: "The ID of the EC2 instance to monitor for MyDashboard1"

  ClusterNameForMyFargateCluster3:
    Description: The name of the ECS cluster
    Type: String
    Default: MyFargateCluster3
  ClusterNameForMyFargateCluster4:
    Description: The name of the ECS cluster
    Type: String
    Default: MyFargateCluster4
  ClusterNameForMyFargateCluster5:
    Description: The name of the ECS cluster
    Type: String
    Default: MyFargateCluster5
  ContainerImageForMyTaskDefinitionFargate1:
    Type: String
    Description: Docker image for the container for MyTaskDefinitionFargate1
    Default: nginx:latest
  ContainerPortForMyTaskDefinitionFargate1:
    Type: Number
    Description: Port exposed by the container for MyTaskDefinitionFargate1
    Default: 80

  ContainerImageForMyTaskDefinitionFargate2:
    Type: String
    Description: Docker image for the container for MyTaskDefinitionFargate2
    Default: nginx:latest
  ContainerPortForMyTaskDefinitionFargate2:
    Type: Number
    Description: Port exposed by the container for MyTaskDefinitionFargate2
    Default: 80

  ContainerImageForMyTaskDefinitionFargate3:
    Type: String
    Description: Docker image for the container for MyTaskDefinitionFargate3
    Default: nginx:latest
  ContainerPortForMyTaskDefinitionFargate3:
    Type: Number
    Description: Port exposed by the container for MyTaskDefinitionFargate3
    Default: 80

  ContainerImageForMyTaskDefinitionFargate4:
    Type: String
    Description: Docker image for the container for MyTaskDefinitionFargate4
    Default: nginx:latest
  ContainerPortForMyTaskDefinitionFargate4:
    Type: Number
    Description: Port exposed by the container for MyTaskDefinitionFargate4
    Default: 80

  ContainerImageForMyTaskDefinitionFargate5:
    Type: String
    Description: Docker image for the container for MyTaskDefinitionFargate5
    Default: nginx:latest
  ContainerPortForMyTaskDefinitionFargate5:
    Type: Number
    Description: Port exposed by the container for MyTaskDefinitionFargate5
    Default: 80

  VPCCidrBlockForMyVPC1:
    Description: The CIDR block for the VPC
    Type: String
    Default: 10.0.0.0/16
    AllowedPattern: '^(([0-9]{1,3})\.){3}[0-9]{1,3}/([0-9]|[1-2][0-9]|3[0-2])$'
    ConstraintDescription: Must be a valid CIDR block.
  ClusterNameForMyCluster1:
    Description: The name of the ECS cluster
    Type: String
    Default: MyCluster1
  TopicNameForMyTopic1:
    Type: String
    Default: "MyTopic1Topic"
    Description: "The name of the SNS topic for MyTopic1."
  DisplayNameForMyTopic1:
    Type: String
    Default: "MyTopic1DisplayName"
    Description: "The display name for the SNS topic for MyTopic1."


  TargetGroupNameForMyTargetGroup1:
    Type: String
    Default: MyTargetGroup1
    Description: Name for the Target Group for MyTargetGroup1

  TargetGroupNameForMyTargetGroup2:
    Type: String
    Default: MyTargetGroup2
    Description: Name for the Target Group for MyTargetGroup2

  SubnetCidrBlockForMySubnet1:
    Description: The CIDR block for the new subnet
    Type: String
    Default: 10.0.1.0/24
    AllowedPattern: '^(([0-9]{1,3})\.){3}[0-9]{1,3}/([0-9]|[1-2][0-9]|3[0-2])$'
    ConstraintDescription: Must be a valid CIDR block.
  AvailabilityZoneForMySubnet1:
    Description: The Availability Zone for the subnet
    Type: String
    Default: us-east-1a  # Replace with your desired AZ
  AlarmThresholdForMyAlarm1:
    Type: Number
    Default: 70
    Description: "The CPU utilization percentage threshold to trigger the alarm for MyAlarm1"







Resources: 
  MyBucket1:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketNameForMyBucket1
      VersioningConfiguration:
        Status: !If 
          - VersioningEnabledForMyBucket1 
          - Enabled 
          - Suspended
  MyFargateCluster1:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: !Ref ClusterNameForMyFargateCluster1
  MyBucket2:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketNameForMyBucket2
      VersioningConfiguration:
        Status: !If 
          - VersioningEnabledForMyBucket2 
          - Enabled 
          - Suspended
  MyFargateCluster2:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: !Ref ClusterNameForMyFargateCluster2
  MyDashboard1:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: 'MyDashboard1'
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/EC2", "CPUUtilization", "InstanceId", "${InstanceIdForMyDashboard1}" ]
                ],
                "period": 300,
                "stat": "Average",
                "region": "${AWS::Region}",
                "title": "EC2 Instance CPU for MyDashboard1"
              }
            }
          ]
        }

  MyFargateCluster3:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: !Ref ClusterNameForMyFargateCluster3
  MyFargateCluster4:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: !Ref ClusterNameForMyFargateCluster4
  MyFargateCluster5:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: !Ref ClusterNameForMyFargateCluster5
  MyRestApi1:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: MyRestApi1
      Description: API for my Lambda function MyRestApi1
  MyTaskDefinitionFargate1:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: fargate-task
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Name: fargate-app-MyTaskDefinitionFargate1
          Image: !Ref ContainerImageForMyTaskDefinitionFargate1
          PortMappings:
            - ContainerPort: !Ref ContainerPortForMyTaskDefinitionFargate1
  MyTaskDefinitionFargate2:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: fargate-task
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Name: fargate-app-MyTaskDefinitionFargate2
          Image: !Ref ContainerImageForMyTaskDefinitionFargate2
          PortMappings:
            - ContainerPort: !Ref ContainerPortForMyTaskDefinitionFargate2
  MyTaskDefinitionFargate3:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: fargate-task
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Name: fargate-app-MyTaskDefinitionFargate3
          Image: !Ref ContainerImageForMyTaskDefinitionFargate3
          PortMappings:
            - ContainerPort: !Ref ContainerPortForMyTaskDefinitionFargate3
  MyTaskDefinitionFargate4:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: fargate-task
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Name: fargate-app-MyTaskDefinitionFargate4
          Image: !Ref ContainerImageForMyTaskDefinitionFargate4
          PortMappings:
            - ContainerPort: !Ref ContainerPortForMyTaskDefinitionFargate4
  MyTaskDefinitionFargate5:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: fargate-task
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Name: fargate-app-MyTaskDefinitionFargate5
          Image: !Ref ContainerImageForMyTaskDefinitionFargate5
          PortMappings:
            - ContainerPort: !Ref ContainerPortForMyTaskDefinitionFargate5
  MyRoleForLambda1:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecutionForMyRoleForLambda1
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
  MyVPC1:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: !Ref VPCCidrBlockForMyVPC1
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MyVPC1
  MyCluster1:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: !Ref ClusterNameForMyCluster1
  MyTopic1:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: !Ref TopicNameForMyTopic1
      DisplayName: !Ref DisplayNameForMyTopic1

  MyBucketPolicy1:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref MyBucket1
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${MyBucket1.Arn}/*"
            Condition:
              Bool:
                "aws:SecureTransport": "true"
            # Example condition for allowing secure transport only
  MyBucketPolicy2:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref MyBucket2
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${MyBucket2.Arn}/*"
            Condition:
              Bool:
                "aws:SecureTransport": "true"
            # Example condition for allowing secure transport only
  MyDistribution1:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultCacheBehavior:
          ViewerProtocolPolicy: redirect-to-https
          TargetOriginId: MyRestApi1
          ForwardedValues:
            QueryString: false
          MinTTL: 0
          DefaultTTL: 300
          MaxTTL: 1200
        Origins:
          - Id: MyRestApi1
            DomainName: !Sub "${MyRestApi1}.execute-api.${AWS::Region}.amazonaws.com"
            OriginPath: /prod
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only

  MyResource1:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      ParentId: !GetAtt MyRestApi1.RootResourceId
      RestApiId: !Ref MyRestApi1
      PathPart: hello
  MyFunction1:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: MySimpleFunctionForMyFunction1
      Handler: index.handler
      Role: !GetAtt MyRoleForLambda1.Arn
      Code:
        ZipFile: |
          def handler(event, context):
            return {
              'statusCode': 200,
              'body': 'Hello, World!'
            }
      Runtime: python3.9
      Timeout: 10
  MyTargetGroup1:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Ref TargetGroupNameForMyTargetGroup1
      Port: 80
      Protocol: TCP
      VpcId: !Ref MyVPC1
      TargetType: ip

  MyTargetGroup2:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Ref TargetGroupNameForMyTargetGroup2
      Port: 80
      Protocol: TCP
      VpcId: !Ref MyVPC1
      TargetType: ip

  MySubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref MyVPC1
      CidrBlock: !Ref SubnetCidrBlockForMySubnet1
      AvailabilityZone: !Ref AvailabilityZoneForMySubnet1
      MapPublicIpOnLaunch: true  # Set to true if you want instances to have public IPs by default
      Tags:
        - Key: Name
          Value: MySubnet1
  MyAlarm1:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: HighCPUAlarmMyAlarm1
      AlarmDescription: Alarm if CPU exceeds the specified threshold for MyAlarm1
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: !Ref AlarmThresholdForMyAlarm1
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: InstanceId
          Value: !Ref InstanceIdForMyDashboard1
      AlarmActions:
        - !Ref MyTopic1

  MyMethodForCloudfront1:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MyRestApi1
      ResourceId: !Ref MyResource1
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationHttpMethod: GET
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              application/json: '{"message": "Hello from API Gateway!"}'
      MethodResponses:
        - StatusCode: 200

  MyMethodForLambda1:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      HttpMethod: GET
      ResourceId: !Ref MyRestApi1
      RestApiId: !Ref MyResource1
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyFunction1.Arn}/invocations
      MethodResponses:
        - StatusCode: 200
  MyPermission1:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref MyFunction1
      Principal: apigateway.amazonaws.com
  MyServiceFargate1:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: MyServiceFargate1
      Cluster: !Ref MyCluster1
      TaskDefinition: !Ref MyTaskDefinitionFargate1
      DesiredCount: 2
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref MySubnet1

  MyServiceFargate2:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: MyServiceFargate2
      Cluster: !Ref MyCluster1
      TaskDefinition: !Ref MyTaskDefinitionFargate2
      DesiredCount: 2
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref MySubnet1

  MyServiceFargate3:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: MyServiceFargate3
      Cluster: !Ref MyCluster1
      TaskDefinition: !Ref MyTaskDefinitionFargate3
      DesiredCount: 2
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref MySubnet1

  MyServiceFargate4:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: MyServiceFargate4
      Cluster: !Ref MyCluster1
      TaskDefinition: !Ref MyTaskDefinitionFargate4
      DesiredCount: 2
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref MySubnet1

  MyServiceFargate5:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: MyServiceFargate5
      Cluster: !Ref MyCluster1
      TaskDefinition: !Ref MyTaskDefinitionFargate5
      DesiredCount: 2
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref MySubnet1

Outputs: 
  S3BucketNameForMyBucket1:
    Description: The name of the created S3 bucket for MyBucket1
    Value: !Ref MyBucket1
  S3BucketArnForMyBucket1:
    Description: The ARN of the created S3 bucket for MyBucket1
    Value: !GetAtt MyBucket1.Arn
  ClusterNameOutputForMyFargateCluster1:
    Description: The name of the created ECS cluster for MyFargateCluster1
    Value: !Ref MyFargateCluster1
  S3BucketNameForMyBucket2:
    Description: The name of the created S3 bucket for MyBucket2
    Value: !Ref MyBucket2
  S3BucketArnForMyBucket2:
    Description: The ARN of the created S3 bucket for MyBucket2
    Value: !GetAtt MyBucket2.Arn
  ClusterNameOutputForMyFargateCluster2:
    Description: The name of the created ECS cluster for MyFargateCluster2
    Value: !Ref MyFargateCluster2
  DashboardURLForMyDashboard1:
    Description: 'URL of the CloudWatch Dashboard for MyDashboard1'
    Value: !Sub 'https://${AWS::Region}.console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=MyDashboard1'
  ClusterNameOutputForMyFargateCluster3:
    Description: The name of the created ECS cluster for MyFargateCluster3
    Value: !Ref MyFargateCluster3
  ClusterNameOutputForMyFargateCluster4:
    Description: The name of the created ECS cluster for MyFargateCluster4
    Value: !Ref MyFargateCluster4
  ClusterNameOutputForMyFargateCluster5:
    Description: The name of the created ECS cluster for MyFargateCluster5
    Value: !Ref MyFargateCluster5
  ApiUrlForMyRestApi1:
    Description: URL for the API Gateway for MyRestApi1
    Value: !Sub "https://${MyRestApi1}.execute-api.${AWS::Region}.amazonaws.com/prod/hello"





  VPCId:
    Description: The ID of the created VPC for MyVPC1
    Value: !Ref MyVPC1
  ClusterNameOutputForMyCluster1:
    Description: The name of the created ECS cluster for MyCluster1
    Value: !Ref MyCluster1
  TopicArnForMyTopic1:
    Description: "The ARN of the SNS topic for MyTopic1."
    Value: !Ref MyTopic1
  TopicNameOutputForMyTopic1:
    Description: "The name of the SNS topic for MyTopic1."
    Value: !Ref TopicNameForMyTopic1
  CloudFrontDomainNameForMyDistribution1:
    Description: Domain name of the CloudFront distribution for MyDistribution1
    Value: !GetAtt MyDistribution1.DomainName
  LambdaFunctionArnForMyFunction1:
    Description: The ARN of the Lambda function for MyFunction1
    Value: !GetAtt MyFunction1.Arn


  SubnetId:
    Description: The ID of the created subnet for MySubnet1
    Value: !Ref MySubnet1
  AlarmNameForMyAlarm1:
    Description: 'Name of the CloudWatch Alarm for MyAlarm1'
    Value: !Ref MyAlarm1


  ServiceNameForMyServiceFargate1:
    Description: ECS Service Name for MyServiceFargate1
    Value: !Ref MyServiceFargate1

  ServiceNameForMyServiceFargate2:
    Description: ECS Service Name for MyServiceFargate2
    Value: !Ref MyServiceFargate2

  ServiceNameForMyServiceFargate3:
    Description: ECS Service Name for MyServiceFargate3
    Value: !Ref MyServiceFargate3

  ServiceNameForMyServiceFargate4:
    Description: ECS Service Name for MyServiceFargate4
    Value: !Ref MyServiceFargate4

  ServiceNameForMyServiceFargate5:
    Description: ECS Service Name for MyServiceFargate5
    Value: !Ref MyServiceFargate5

