apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: diagrams2code
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        image: capthestone/api-gateway:latest
        envFrom:
        - configMapRef:
            name: kafka-config
        - configMapRef:
            name: redis-config
        ports:
        - containerPort: 8000
